name: delivery frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
jobs:
  delivery:
    runs-on: [self-hosted]
    env:
      IMAGE_NAME: wolfort-games-frontend
    steps:
      - name: setup
        run: |
          docker image prune --force

      - name: clone repository
        uses: actions/checkout@v2

      - name: build
        run: >
          docker build
          -t ghcr.io/h-orito/${{ env.IMAGE_NAME }}:latest ./frontend
          --build-arg AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          --build-arg AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
          --build-arg AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          --build-arg GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT }}
          --build-arg GRAPHQL_INNER_ENDPOINT=${{ secrets.GRAPHQL_INNER_ENDPOINT }}
      - name: deploy
        run: |
          docker login ghcr.io -u h-orito -p ${{ secrets.PACKAGE_PAT }}
          docker push ghcr.io/h-orito/${{ env.IMAGE_NAME }}
      - name: release
        run: |
          kubectl delete pod -l app=wolfort-games-frontend
